name: Tag Release
on:
    push:
        branches: [ main ]
jobs:
    tag_release:
        name: Create Release And Upload Apk
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v1
            with:
              java-version: "12.x"
          - uses: subosito/flutter-action@v2
            with:
              flutter-version: '3.x'
          - run: flutter pub get
          - run: flutter clean
          - run: flutter build apk --split-per-abi
          - id: read-version
            uses: NiklasLehnfeld/flutter-version-number-action@main
            with:
              file-path: ${{github.workspace}}/pubspec.yaml
          - uses: nick-invision/assert-action@v1
          - uses: ffurrer2/extract-release-notes@v1
            with:
              changelog_file: ${{github.workspace}}/CHANGELOG.md
          - uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                tag_name: ${{ steps.read-version.outputs.version-number }}
                release_name: v${{ steps.read-version.outputs.version-number }}
                body: ${{ steps.extract_release_notes.outputs.release_notes }}
                draft: false
                prerelease: false
          - uses: actions/upload-release-asset@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
              asset_path: ${{github.workspace}}/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
              asset_name: my-artifact.zip
              asset_content_type: application/zip