name: Tag Release
on:
    push:
        branches: [ main ]
jobs:
    tag_release:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Initialize mandatory git config
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email noreply@github.com
            - name: Setup release information
              #get version name from app_versions.gradle file (5.6.2)
              run: |
                 - run: echo "VERSION_INFORMATION=$(${{github.workspace}}/android/app/build.gradle -q printVersionInformation)" >> $GITHUB_ENV
            - name: Extract release notes
              id: extract_release_notes
              uses: ffurrer2/extract-release-notes@v1
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ env.VERSION_INFORMATION }}
                release_name: v${{ env.VERSION_INFORMATION }}
                body: ${{ steps.extract_release_notes.outputs.release_notes }}
                draft: false
                prerelease: false